name: lint-and-build
on:
  push:
    branches:
      - '*'
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: stefanoeb/eslint-action@master
        with:
          args: . --ext .ts,.tsx
      - name: build
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
        with:
          args: npx gatsby build
