name: lint-and-build
on:
  push:
    branches:
      - '*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npx yarn install
      - run: npx eslint . --ext .ts,.tsx --ignore-path .eslintignore
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npx yarn install
      - run: npx gatsby build
        env:
          API_KEY: ${{ secrets.API_KEY }}
