name: lint-and-build
on:
  push:
    branches:
      - '*'
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: stefanoeb/eslint-action@master
        with:
          args: . --ext .ts,.tsx
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npx yarn install
      - run: npx gatsby build
        env:
          API_KEY: ${{ secrets.API_KEY }}
