on: push
name: lint and build
jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: lint
        uses: stefanoeb/eslint-action@master
        with:
          args: . --ext .ts,.tsx
      - name: build
        uses: kiralybalint/gatsby-cli-github-action@master
        with:
          args: build
